### ISSUE TITLE
from google.colab import drive

### ISSUE THREAD

**Issue by kelikeli** [VBhat97/AdCOFE#1]
When I run these lines “from google.colab import drive
drive.mount('/content/gdrive')”of code, I get an error:
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhiyu601/anaconda3/envs/skl36/lib/python3.6/site-packages/google/colab/drive.py", line 82, in mount
    env = _env()
  File "/home/zhiyu601/anaconda3/envs/skl36/lib/python3.6/site-packages/google/colab/drive.py", line 43, in _env
    _os.path.join(_os.environ['CLOUDSDK_CONFIG'], '../..'))
  File "/home/zhiyu601/anaconda3/envs/skl36/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CLOUDSDK_CONFIG'

**Comment by VBhat97** [comment]
Hi, The code has been further updated so you can include code from local space and no drive mounts are required. Kindly give it a try! Thanks.
